## 第四章 Numpy基础

### 4.1 NumPy的ndarray：一种多维数组对象

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.41010472, -0.39984794, -1.11174548],
       [-0.78978391,  0.46454366, -0.19094013]])

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

### 4.2 创建ndarray

In [5]:
data2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2.ndim

2

### 4.3 数组转换和轴兑换

In [7]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [9]:
arr2 = np.arange(16).reshape((2, 2, 4))
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr2.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

### 4.4 用于数组的文件输入输出

In [11]:
arr = np.arange(10)
np.save('arr', arr)

In [12]:
np.load('arr.npy')     # 默认保存成后缀为npy的文件

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

通过`np.savez`可以将多个数组保存到一个`未压缩`文件中，将数组以关键字参数的形式传入即可：

In [13]:
np.savez('arr_archive.npz', a=arr, b=arr)

In [15]:
arch = np.load('arr_archive.npz')

In [16]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

如果想要将数据压缩，可以使用np.savez_compressed

## 第五章 pandas入门

### 5.1 pandas数据结构介绍

要使用pandas，你首先就得熟悉它的两个主要数据结构：`Series`和`DataFrame`

+ Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成

+ DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有`行索引也有列索引`，它可以被看做由Series组成的字典（共用同一个索引）。DataFrame中的数据是以一个或多个二维块存放的（而不是列表、字典或别的一维数据结构）。

In [17]:
import pandas as pd

In [18]:
obj = pd.Series([4., 7, -5, 3])
obj

0    4.0
1    7.0
2   -5.0
3    3.0
dtype: float64

In [19]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [20]:
obj.values

array([ 4.,  7., -5.,  3.])

In [21]:
obj.dtype

dtype('float64')

也可以在创建的时候指定`index`和`dtype`

In [22]:
obj2 = pd.Series([1, 2, 3], index=list("abc"), dtype=np.int64)

In [23]:
obj2

a    1
b    2
c    3
dtype: int64

也可以通过字典进行创建series

In [24]:
 sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [25]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Series最重要的一个功能是，它会根据运算的`索引标签自动对齐数据`

In [27]:
obj3.index = list("ABCD")    # 可以就地修改index
obj3

A    35000
B    71000
C    16000
D     5000
dtype: int64

第一种创建方式，传入一个等长列表组成的字典

In [28]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [29]:
df = pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [30]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [31]:
df.columns

Index(['state', 'year', 'pop'], dtype='object')

可以指定列顺序，这样就可以按照列的顺序进行排列了

In [32]:
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
df = pd.DataFrame(data, columns=['year', 'state', 'pop'])
df

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

如果传入的列在数据中找不到，就会产生缺失值

In [35]:
df2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

行索引
+ .loc[index]

列索引
+ df[column]

In [36]:
df2.debt = 15.6
df2

year   state  pop  debt
one    2000    Ohio  1.5  15.6
two    2001    Ohio  1.7  15.6
three  2002    Ohio  3.6  15.6
four   2001  Nevada  2.4  15.6
five   2002  Nevada  2.9  15.6
six    2003  Nevada  3.2  15.6

In [37]:
df2.debt = np.arange(6)
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

删除列的方法 del df[column]

### 5.2 基本功能

+ 重新索引(之前没有的索引，对应的值是NAN)

In [38]:
obj = pd.Series([4.5, 7.2, -5.3], index=['a', 'b', 'c'])
obj

a    4.5
b    7.2
c   -5.3
dtype: float64

In [39]:
obj = obj.reindex(['a', 'b', 'c', 'd'])
obj

a    4.5
b    7.2
c   -5.3
d    NaN
dtype: float64

In [40]:
frame = pd.DataFrame(
        np.arange(9).reshape((3, 3)),
        index=['a', 'c', 'd'],
        columns=['Ohio', 'Texas', 'Colifornia']
)

In [41]:
frame

Ohio  Texas  Colifornia
a     0      1           2
c     3      4           5
d     6      7           8

In [42]:
frame = frame.reindex(['a', 'b', 'c', 'd'])
frame

Ohio  Texas  Colifornia
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [46]:
state = ['Texas', 'Utah', 'California']
frame.reindex(columns=state)

Texas  Utah  California
a    1.0   NaN         NaN
b    NaN   NaN         NaN
c    4.0   NaN         NaN
d    7.0   NaN         NaN

+ 丢弃指定轴上的项

In [53]:
obj = pd.Series(np.arange(5), index=list("abcde"))
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [54]:
obj.drop('b', inplace=True)    # 带上inplace=True，最后的结果相当于在原结果中进行修改

In [55]:
obj

a    0
c    2
d    3
e    4
dtype: int32

In [56]:
data =  pd.DataFrame(np.arange(16).reshape((4, 4)),
                        index=['Ohio', 'Colorado', 'Utah', 'New York'],
                        columns=['one', 'two', 'three', 'four'])

In [58]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data.drop(['Ohio'])    # 默认删除的是行索引

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
data.drop(['one'], axis=1)    # axis=1,相当于指定了删除的对象

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

+ 索引、选取和过滤

In [63]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [65]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [66]:
obj['a']

0.0

In [67]:
obj[:2]

a    0.0
b    1.0
dtype: float64

In [68]:
obj[['a', 'b', 'c']]

a    0.0
b    1.0
c    2.0
dtype: float64

In [69]:
obj[obj>2]

d    3.0
dtype: float64

In [70]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                       index=['Ohio', 'Colorado', 'Utah', 'New York'],
                       columns=['one', 'two', 'three', 'four'])

In [71]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [73]:
data.two

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [76]:
data[:2]    # 第一个引号是对行进行索引

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [80]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.loc[:'Utah', :'three']    # 不同于数字切片，索引值进行切片的时候最后一个是包括的

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10

In [85]:
data.iloc[:2, :3]    # iloc对应的是坐标，最后一个是不包括的

one  two  three
Ohio        0    1      2
Colorado    4    5      6

+ 函数应用和映射

In [86]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [87]:
frame

b         d         e
Utah    0.582523  0.080457 -0.360883
Ohio   -0.588653 -0.498618 -0.321286
Texas   0.228620 -0.041806 -0.785438
Oregon -0.150165  1.440299 -0.649238

In [88]:
np.abs(frame)

b         d         e
Utah    0.582523  0.080457  0.360883
Ohio    0.588653  0.498618  0.321286
Texas   0.228620  0.041806  0.785438
Oregon  0.150165  1.440299  0.649238

In [90]:
frame.apply(lambda x: x.max()-x.min())    # 默认是作用在列上面

b    1.171176
d    1.938917
e    0.464153
dtype: float64

In [92]:
frame.apply(lambda x: x.max()-x.min(), axis='columns')     # 这样会在每行执行

Utah      0.943406
Ohio      0.267367
Texas     1.014058
Oregon    2.089537
dtype: float64

+ apply 函数作用在`一行或者一列`

+ applymap 函数作用在`每个元素`上

+ 排序和排名

In [93]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [94]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [96]:
obj.sort_index()    # 按照索引进行排序

a    1
b    2
c    3
d    0
dtype: int64

In [98]:
obj.sort_values()    # 按照值进行排序

d    0
a    1
b    2
c    3
dtype: int64